### ISSUE TITLE
Additional Homekit Button to disable realtime

### ISSUE THREAD

**Issue by LeLunZ** [smhex/homebridge-wled-ws#78] opened 2024-05-15 10:50 UTC
**Is your feature request related to a problem? Please describe:**
I am currently using wled as a tv backlight. I have a setup with hyperion.ng where it changes the colors according to whats shown on my tv screen. 

Sometimes when watching tv the live backlight doesn't make sense, because of the fast pace of the movie or other influences.

So it would be great if there was a nice simple option through homekit to disable the realtime sync of wled through homekit.

**Describe the solution you'd like:**
Add a additional on/off button to the accessory.
(When pressing on/off, we just need to set the "live" property to "true"/"false")

I can also create a PR myself :) just wanted to check if thats okay with you.

**Comment by smhex** [comment] 2024-05-15 16:32
Hi @LeLunZ , no problem - it sounds like a useful feature. Personally I don't use it (yet). However, my code is hopefully self explaining enough so that you can add the required logic. It would be nice to make this feature configurable through the plugin's settings dialog. In case of questions - just ask 😀

**Comment by LeLunZ** [comment] 2024-05-15 17:21
Okay just looked through the code. Its not feature/ws. There is too much code commented out xD

**Comment by smhex** [comment] 2024-05-15 17:28
The ws branch addresses the replacement of the Wled-client library. I am not sure if I proceed here😀. You can start from /dev or (later that day) from main after I created the next release...

**Comment by LeLunZ** [comment] 2024-05-15 17:29
Is there a reason why you want to replace the client library? 
My Guess, would be: Too much overhead?

**Comment by smhex** [comment] 2024-05-15 18:20
There was this WLED firmware issues with 0.14.2 and I wasn't sure where the root cause was located. One potential cause would have been this library. It turned out that the reason was WLED itself. However, I do not use much of the library functions at the moment. Replacing it with the native ws package could reduce another dependency...

**Comment by smhex** [comment] 2024-05-15 18:22
...I just released 0.0.13. You can start your work branching main.

**Comment by smhex** [comment] 2024-05-16 05:23
Merged PR #79

**Closed by smhex** 2024-05-16 05:23 UTC
Labels: enhancement
