### ISSUE TITLE
Wrong reported brightness

### ISSUE THREAD

**Issue by Hansjshx** [smhex/homebridge-wled-ws#12] opened 2024-01-24 18:33 UTC
**Describe The Bug:**
This plugin generated a warning from the characteristic 'Brightness': characteristic was supplied illegal value: number 199 exceeded maximum of 100.

**To Reproduce:**
every time the accessory  is initialized
 
**Expected behavior:**
Conversion from WLED brightness range (0-255) to 0-100

**Logs:**

```
[1/24/2024, 7:28:05 PM] [wled-ws platform] Get Characteristic On -> true
[1/24/2024, 7:28:05 PM] [wled-ws platform] Get Characteristic Brightness -> 199
[1/24/2024, 7:28:05 PM] [homebridge-wled-ws] This plugin generated a warning from the characteristic 'Brightness': characteristic was supplied illegal value: number 199 exceeded maximum of 100. See https://homebridge.io/w/JtMGR for more info.
```

**Plugin Config:**

            "name": "wled-ws platform",
            "controllers": [
                {
                    "name": "Dampfmaschine",
                    "address": "192.168.178.119"
                }
            ],
            "logging": false,
            "platform": "wled-ws"
        }

**Screenshots:**

**Environment:**

* Plugin Version: 0.0.5
* **Homebridge Version**: 1.7.0
* **Node.js Version**: v18.13.0
* **NPM Version**: 8.19.3
* **Operating System**: Docker

**Comment by smhex** [comment] 2024-01-25 00:04
Duplicate of #7 .  This is already fixed. Please try the latest beta. Thank you 🙏

**Closed by smhex** 2024-01-25 00:04 UTC
Labels: bug
